"""Bilingual string system — Arabic / English"""
import streamlit as st

STRINGS: dict[str, dict[str, str]] = {
    "ar": {
        # Nav
        "site_title":        "Titan OSINT",
        "subtitle":          "منصة الاستخبارات السيبرانية • 33 محرك • ذكاء اصطناعي",
        "lang_btn":          "🌐 English",
        # Sidebar
        "scan_section":      "المسح",
        "target_ph":         "IP / نطاق / بريد / Hash / ASN / GitHub / npm",
        "mode_single":       "هدف واحد",
        "mode_bulk":         "جماعي",
        "bulk_ph":           "8.8.8.8\nexample.com\nuser@email.com",
        "cache_chk":         "⚡ كاش (6 ساعات)",
        "scan_btn":          "▶ تشغيل المحركات",
        "status_section":    "الحالة",
        "engines_section":   "المحركات",
        "history_section":   "السجل",
        "bookmarks_section": "المفضلة",
        "no_history":        "لا توجد عمليات مسح",
        "no_bookmarks":      "لا توجد مفضلة",
        "apis_configured":   "APIs مفعّلة",
        "ai_engine":         "محرك الذكاء",
        # Tabs
        "tab_dash":    "📊 لوحة التحكم",
        "tab_signals": "🎯 الإشارات",
        "tab_dev":     "💻 المطوّر",
        "tab_geo":     "🗺️ الخريطة",
        "tab_graph":   "🕸️ الشبكة",
        "tab_raw":     "🔍 البيانات",
        "tab_ai":      "🧠 TitanAI",
        "tab_history": "📈 التاريخ",
        "tab_mitre":   "⚔️ MITRE",
        # Dashboard
        "threat_score":    "درجة التهديد",
        "threat_level":    "مستوى التهديد",
        "bookmark_btn":    "⭐ مفضلة",
        "bookmarked_ok":   "تمت الإضافة",
        "infra_card":      "البنية التحتية",
        "geo_card":        "الموقع الجغرافي",
        "metric_abuse":    "AbuseIPDB",
        "metric_vt":       "VT ضار",
        "metric_ports":    "منافذ مفتوحة",
        "metric_pulses":   "نبضات OTX",
        "metric_ioc":      "ThreatFox IOC",
        "metric_score":    "الدرجة",
        # Signals
        "signals_title":   "الإشارات النشطة",
        "no_signals":      "✅ لا توجد إشارات تهديد",
        "engine_results":  "نتائج المحركات",
        "ioc_title":       "مؤشرات الاختراق (IOCs)",
        # Dev
        "dev_title":       "تحليل المطوّر — GitHub / npm / PyPI / Git",
        "github_title":    "GitHub",
        "npm_title":       "npm Package",
        "pypi_title":      "PyPI Package",
        "crt_title":       "شهادات SSL (crt.sh)",
        "wayback_title":   "Wayback Machine",
        "no_github_key":   "⚠️ أضف GITHUB_TOKEN في .env للبيانات الكاملة",
        # AI
        "ai_title":        "تحليل TitanAI",
        "ai_loading":      "TitanAI يحلل جميع المصادر...",
        "ai_quota_msg":    "⚠️ تجاوزت حصة OpenAI — أضف GEMINI_KEY في .env",
        "ai_no_key":       "⚠️ لا يوجد مفتاح AI",
        # Downloads
        "dl_txt":          "📄 تحميل TXT",
        "dl_pdf":          "📄 تحميل PDF",
        "dl_json":         "📥 JSON",
        "dl_ioc":          "📥 IOCs CSV",
        "dl_csv":          "📥 CSV",
        "dl_mitre":        "📥 MITRE CSV",
        # Misc
        "cache_hit":       "⚡ من الكاش (أقل من 6 ساعات)",
        "engines_done":    "✓ اكتملت جميع المحركات",
        "bulk_results":    "نتائج المسح الجماعي",
        "standby_msg":     "محركات الاستخبارات في وضع الاستعداد",
        "history_title":   "سجل عمليات المسح",
        "mitre_title":     "تقنيات MITRE ATT&CK",
        "no_mitre":        "لا توجد تقنيات مرتبطة بهذا الهدف",
        "geo_no_data":     "لا توجد إحداثيات — جرّب هدف IP",
        "graph_no_data":   "بيانات العلاقات غير كافية",
        "notes_ph":        "أضف ملاحظة عن هذا الهدف...",
        "save_note":       "💾 حفظ الملاحظة",
        "note_saved":      "تم الحفظ",
        "chat_ph":         "اسأل TitanAI عن أي تهديد...",
        "no_result":       "لا توجد نتائج",
        "total_scans":     "إجمالي المسح",
        "critical_alerts": "تنبيهات حرجة",
        "today_scans":     "اليوم",
        "unique_targets":  "أهداف فريدة",
    },
    "en": {
        "site_title":        "Titan OSINT",
        "subtitle":          "Cyber Intelligence Platform • 33 Engines • AI Fusion",
        "lang_btn":          "🌐 العربية",
        "scan_section":      "SCAN",
        "target_ph":         "IP / Domain / Email / Hash / ASN / GitHub / npm",
        "mode_single":       "Single",
        "mode_bulk":         "Bulk",
        "bulk_ph":           "8.8.8.8\nexample.com\nuser@email.com",
        "cache_chk":         "⚡ Cache (6h)",
        "scan_btn":          "▶ RUN ENGINES",
        "status_section":    "STATUS",
        "engines_section":   "ENGINES",
        "history_section":   "HISTORY",
        "bookmarks_section": "BOOKMARKS",
        "no_history":        "No scans yet",
        "no_bookmarks":      "No bookmarks",
        "apis_configured":   "APIs Active",
        "ai_engine":         "AI Engine",
        "tab_dash":    "📊 DASHBOARD",
        "tab_signals": "🎯 SIGNALS",
        "tab_dev":     "💻 DEVELOPER",
        "tab_geo":     "🗺️ GEO MAP",
        "tab_graph":   "🕸️ NETWORK",
        "tab_raw":     "🔍 RAW DATA",
        "tab_ai":      "🧠 TITANAI",
        "tab_history": "📈 HISTORY",
        "tab_mitre":   "⚔️ MITRE",
        "threat_score":    "THREAT SCORE",
        "threat_level":    "THREAT LEVEL",
        "bookmark_btn":    "⭐ Bookmark",
        "bookmarked_ok":   "Bookmarked!",
        "infra_card":      "INFRASTRUCTURE",
        "geo_card":        "GEOLOCATION",
        "metric_abuse":    "Abuse Score",
        "metric_vt":       "VT Malicious",
        "metric_ports":    "Open Ports",
        "metric_pulses":   "OTX Pulses",
        "metric_ioc":      "ThreatFox IOC",
        "metric_score":    "Score",
        "signals_title":   "ACTIVE SIGNALS",
        "no_signals":      "✅ No threat signals detected",
        "engine_results":  "Engine Results",
        "ioc_title":       "EXTRACTED IOCs",
        "dev_title":       "Developer Intel — GitHub / npm / PyPI / Git",
        "github_title":    "GitHub",
        "npm_title":       "npm Package",
        "pypi_title":      "PyPI Package",
        "crt_title":       "SSL Certificates (crt.sh)",
        "wayback_title":   "Wayback Machine",
        "no_github_key":   "⚠️ Add GITHUB_TOKEN in .env for full data",
        "ai_title":        "TitanAI Analysis",
        "ai_loading":      "TitanAI correlating all intelligence sources...",
        "ai_quota_msg":    "⚠️ OpenAI quota exceeded — add GEMINI_KEY to .env",
        "ai_no_key":       "⚠️ No AI key configured",
        "dl_txt":          "📄 Download TXT",
        "dl_pdf":          "📄 Download PDF",
        "dl_json":         "📥 JSON",
        "dl_ioc":          "📥 IOCs CSV",
        "dl_csv":          "📥 CSV",
        "dl_mitre":        "📥 MITRE CSV",
        "cache_hit":       "⚡ Loaded from cache (< 6h)",
        "engines_done":    "✓ All engines complete",
        "bulk_results":    "BULK SCAN RESULTS",
        "standby_msg":     "Intelligence engines standing by",
        "history_title":   "SCAN LOG",
        "mitre_title":     "MITRE ATT&CK MAPPING",
        "no_mitre":        "No ATT&CK techniques mapped",
        "geo_no_data":     "No coordinates — try an IP target",
        "graph_no_data":   "Not enough relationship data",
        "notes_ph":        "Add a note about this target...",
        "save_note":       "💾 Save Note",
        "note_saved":      "Saved!",
        "chat_ph":         "Ask TitanAI about any threat...",
        "no_result":       "No results",
        "total_scans":     "Total Scans",
        "critical_alerts": "Critical Alerts",
        "today_scans":     "Today",
        "unique_targets":  "Unique Targets",
    }
}

def T(key: str) -> str:
    lang = st.session_state.get("lang", "ar")
    return STRINGS.get(lang, STRINGS["ar"]).get(key, key)
