[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
