name: titan_osint
description: Titan OSINT — Cyber Intelligence Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  http: ^1.2.1
  dio: ^5.4.3+1

  # State management
  provider: ^6.1.2

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # Utils
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
